# packageExtensions:
#   '@tanstack/react-query-devtools@*':
#     peerDependencies:
#       '@tanstack/react-query': '^4.0.0'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.2.cjs
